version: '3.7'

services:
  db:
    container_name: db
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: stage
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  backend:
    container_name: backend
    image: backend
    restart: always
    links:
      - db
    ports:
      - '8085:8080'
  front:
    links:
      - backend
    container_name: front
    image: front
    ports:
      - '4200:80'
